/* gen_monarch.pl — generate the editor's keyword lists from the engine's own
   operator table.

   §I.10.1a: "src/core/lps_ops.pl is the single source of the operator list;
   the grammar should be generated from it rather than transcribed, so the two
   cannot drift." This is that generator. It writes a small JavaScript module
   the Monarch grammar imports, and it runs as the first step of the UI build.

     ./myswipl.sh -q -g "consult('tools/gen_monarch.pl')" -g gen_monarch:main -t halt
*/

:- module(gen_monarch, [main/0]).

:- use_module(library(lists)).
:- use_module('../src/core/lps_ops').

out_file('ui/src/generated/lps-vocabulary.js').

%	The operators that are *words* — those are what a syntax highlighter
%	should colour as keywords. Symbolic operators (`::`) are punctuation and
%	are handled by the grammar's symbol rule.
word_operator(Name) :-
	member(Op, [not, then, if, else, terminates, initiates, updates, observe,
		    false, initially, fluents, events, prolog_events, actions,
		    unserializable, update, initiate, terminate, in, at, during,
		    from, to, achieve]),
	Name = Op.

%	Declaration predicates: settings and the visual mappings. These are
%	ordinary predicates rather than operators, but an author reads them as
%	part of the language, so they are coloured as such.
declaration(maxTime).
declaration(maxRealTime).
declaration(minCycleTime).
declaration(simulatedRealTimePerCycle).
declaration(simulatedRealTimeBeginning).
declaration(display).
declaration(display3d).
declaration(lps_engine).

%	The §I.3 internal vocabulary, which a `_.P` or `.lpsw` file is written
%	in. Highlighted differently: seeing `reactive_rule` in a hand-written
%	program usually means the author meant `if … then …`.
internal(reactive_rule).
internal(l_int).
internal(l_events).
internal(l_timeless).
internal(d_pre).
internal(initiated).
internal(terminated).
internal(updated).
internal(initial_state).
internal(happens).
internal(holds).

%	Predicates the engine answers itself.
system_pred(real_time).
system_pred(lps_user).
system_pred(lps_terminate).
system_pred(real_date_begin).
system_pred(real_date_end).
system_pred(end_of_day).
system_pred(findall).

main :-
	out_file(Rel),
	ensure_dir(Rel),
	setup_call_cleanup(
	    open(Rel, write, S, [encoding(utf8)]),
	    write_module(S),
	    close(S)),
	format('wrote ~w~n', [Rel]).

ensure_dir(Rel) :-
	file_directory_name(Rel, Dir),
	( exists_directory(Dir) -> true ; make_directory_path(Dir) ).

write_module(S) :-
	format(S, '/* Generated by tools/gen_monarch.pl from src/core/lps_ops.pl.~n', []),
	format(S, '   Do not edit: run `npm --prefix ui run build`. */~n~n', []),
	list_of(word_operator, Ops),
	list_of(declaration, Decls),
	list_of(internal, Internals),
	list_of(system_pred, Systems),
	emit(S, 'operators', Ops),
	emit(S, 'declarations', Decls),
	emit(S, 'internals', Internals),
	emit(S, 'systemPredicates', Systems),
	%  The real table, for a hover that can say how an operator binds.
	format(S, 'export const operatorTable = [~n', []),
	forall(current_lps_op(P, T, N),
	       format(S, '  { name: "~w", priority: ~w, type: "~w" },~n', [N, P, T])),
	format(S, '];~n', []).

%	current_op/3 takes a *module-qualified name*: the module goes on the
%	third argument, not on the goal. `lps_ops:current_op(P,T,then)` asks the
%	right module the wrong question and quietly answers no.
current_lps_op(P, T, N) :-
	word_operator(N),
	current_op(P, T, gen_monarch:N),
	member(T, [xfx, xfy, yfx, fy, fx, xf, yf]).

list_of(Pred, Sorted) :-
	G =.. [Pred, X],
	findall(X, G, L),
	sort(L, Sorted).

emit(S, Name, List) :-
	format(S, 'export const ~w = [', [Name]),
	forall(nth0(I, List, X),
	       ( ( I =:= 0 -> true ; format(S, ', ', []) ), format(S, '"~w"', [X]) )),
	format(S, '];~n~n', []).
