/* fetch-icons.mjs — download the icon library named in icons/manifest.json.
 *
 * The plan (§I.10.4b) asks for "an offline copy of the chosen subset ships
 * with the image so that a deployment without internet still animates". This
 * is that copy. Run it when the manifest changes:
 *
 *   node ui/fetch-icons.mjs
 *
 * Downloaded files land in ui/static/icons/ and are committed, so neither the
 * build nor the container needs a network.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const manifest = JSON.parse(readFileSync(join(here, 'icons', 'manifest.json'), 'utf8'));
const outdir = join(here, 'static', 'icons');
mkdirSync(outdir, { recursive: true });

const force = process.argv.includes('--force');
let got = 0, kept = 0, failed = [];

for (const icon of manifest.icons) {
  const out = join(outdir, icon.name + '.svg');
  if (existsSync(out) && !force) { kept++; continue; }
  const set = manifest.sets[icon.set];
  if (!set) { failed.push([icon.name, 'unknown set ' + icon.set]); continue; }
  const url = set.url.replace('{id}', icon.id);
  try {
    const r = await fetch(url);
    if (!r.ok) { failed.push([icon.name, `HTTP ${r.status} ${url}`]); continue; }
    let svg = await r.text();
    //  game-icons come as 1em/currentColor; give them a usable default so a
    //  display/2 clause that names no colour still shows something.
    if (icon.set === 'game-icons' || icon.set === 'material-symbols') {
      svg = svg.replace('width="1em" height="1em"', 'width="128" height="128"')
        .replace(/currentColor/g, icon.colour || '#cfd6e4');
    }
    writeFileSync(out, svg);
    got++;
  } catch (e) {
    failed.push([icon.name, e.message]);
  }
}

/* A JS index for the front end and the assistant: name, description and the
 * concepts each icon answers to. This is what "the assistant picks icons by
 * description" means in practice — it reads this, not a search API. */
const index = manifest.icons.map(({ name, set, desc, concepts }) => ({ name, set, desc, concepts }));
mkdirSync(join(here, 'src', 'generated'), { recursive: true });
writeFileSync(join(here, 'src', 'generated', 'icon-index.js'),
  '/* Generated by ui/fetch-icons.mjs from ui/icons/manifest.json. */\n'
  + 'export const iconIndex = ' + JSON.stringify(index, null, 1) + ';\n'
  + 'export const iconLicenses = ' + JSON.stringify(manifest.sets, null, 1) + ';\n');

console.log(`icons: ${got} downloaded, ${kept} already present, ${failed.length} failed`);
for (const [n, why] of failed) console.log(`  ! ${n}: ${why}`);
